# Generated by Django 5.1.3 on 2024-11-18 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('book_2', models.IntegerField()),
                ('book_3', models.IntegerField()),
                ('book_4', models.IntegerField()),
                ('item_1', models.IntegerField()),
                ('item_2', models.IntegerField()),
                ('item_3', models.IntegerField()),
                ('talent_boss', models.IntegerField()),
                ('mora', models.IntegerField()),
                ('crown', models.IntegerField()),
            ],
        ),
    ]
