# Generated by Django 5.1.3 on 2024-11-24 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genshincalc', '0004_elitemob_exp_gem_localspeciality_normalboss_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.IntegerField()),
                ('specialty_id', models.IntegerField()),
                ('gem_id', models.IntegerField()),
                ('boss_id', models.IntegerField()),
                ('weekly_boss_id', models.IntegerField()),
                ('talent_id', models.IntegerField()),
                ('regular_mob_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WeaponMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_id', models.IntegerField()),
                ('weapon_ascension_id', models.IntegerField()),
                ('elite_mob_id', models.IntegerField()),
                ('regular_mob_id', models.IntegerField()),
            ],
        ),
    ]
