# Generated by Django 5.1.3 on 2024-11-24 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genshincalc', '0005_charactermapping_weaponmapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charactermapping',
            name='id',
        ),
        migrations.RemoveField(
            model_name='weaponmapping',
            name='id',
        ),
        migrations.AlterField(
            model_name='charactermapping',
            name='character_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='weaponmapping',
            name='weapon_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
