# Generated by Django 5.1.3 on 2024-11-24 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genshincalc', '0006_remove_charactermapping_id_remove_weaponmapping_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CharacterMapping',
        ),
        migrations.DeleteModel(
            name='WeaponMapping',
        ),
    ]
