# Generated by Django 5.1.3 on 2024-11-24 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genshincalc', '0008_charactermapping_weaponmapping'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CharacterMapping',
        ),
        migrations.DeleteModel(
            name='WeaponMapping',
        ),
    ]
