# Generated by Django 5.1.3 on 2024-11-24 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genshincalc', '0009_delete_charactermapping_delete_weaponmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterMapping',
            fields=[
                ('character_id', models.IntegerField(primary_key=True, serialize=False)),
                ('specialty_id', models.IntegerField()),
                ('boss_id', models.IntegerField()),
                ('weekly_boss_id', models.IntegerField()),
                ('gem_2_id', models.IntegerField()),
                ('gem_3_id', models.IntegerField()),
                ('gem_4_id', models.IntegerField()),
                ('gem_5_id', models.IntegerField()),
                ('talent_2_id', models.IntegerField()),
                ('talent_3_id', models.IntegerField()),
                ('talent_4_id', models.IntegerField()),
                ('regular_mob_1_id', models.IntegerField()),
                ('regular_mob_2_id', models.IntegerField()),
                ('regular_mob_3_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WeaponMapping',
            fields=[
                ('weapon_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ascension_2_id', models.IntegerField()),
                ('ascension_3_id', models.IntegerField()),
                ('ascension_4_id', models.IntegerField()),
                ('ascension_5_id', models.IntegerField()),
                ('elite_mob_2_id', models.IntegerField()),
                ('elite_mob_3_id', models.IntegerField()),
                ('elite_mob_4_id', models.IntegerField()),
                ('regular_mob_1_id', models.IntegerField()),
                ('regular_mob_2_id', models.IntegerField()),
                ('regular_mob_3_id', models.IntegerField()),
            ],
        ),
    ]
