# Generated by Django 5.1.3 on 2024-11-25 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genshincalc', '0010_charactermapping_weaponmapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charactermapping',
            name='gem_3_id',
        ),
        migrations.RemoveField(
            model_name='charactermapping',
            name='gem_4_id',
        ),
        migrations.RemoveField(
            model_name='charactermapping',
            name='gem_5_id',
        ),
        migrations.RemoveField(
            model_name='charactermapping',
            name='regular_mob_2_id',
        ),
        migrations.RemoveField(
            model_name='charactermapping',
            name='regular_mob_3_id',
        ),
        migrations.RemoveField(
            model_name='charactermapping',
            name='talent_3_id',
        ),
        migrations.RemoveField(
            model_name='charactermapping',
            name='talent_4_id',
        ),
    ]
