# Generated by Django 5.1.3 on 2024-11-25 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genshincalc', '0011_remove_charactermapping_gem_3_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weaponmapping',
            name='ascension_3_id',
        ),
        migrations.RemoveField(
            model_name='weaponmapping',
            name='ascension_4_id',
        ),
        migrations.RemoveField(
            model_name='weaponmapping',
            name='ascension_5_id',
        ),
        migrations.RemoveField(
            model_name='weaponmapping',
            name='elite_mob_3_id',
        ),
        migrations.RemoveField(
            model_name='weaponmapping',
            name='elite_mob_4_id',
        ),
        migrations.RemoveField(
            model_name='weaponmapping',
            name='regular_mob_2_id',
        ),
        migrations.RemoveField(
            model_name='weaponmapping',
            name='regular_mob_3_id',
        ),
    ]
