# Generated by Django 5.1.3 on 2024-11-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genshincalc', '0013_ascension_remove_talent_id_alter_talent_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharCalc',
            fields=[
                ('level', models.IntegerField(choices=[(1, 1), (20, 20), (40, 40), (50, 50), (60, 60), (70, 70), (80, 80), (90, 90)], default=1, primary_key=True, serialize=False)),
                ('na', models.BooleanField(default=True)),
                ('na_from', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1)),
                ('na_to', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=10)),
                ('skill', models.BooleanField(default=True)),
                ('skill_from', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1)),
                ('skill_to', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=10)),
                ('burst', models.BooleanField(default=True)),
                ('burst_from', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1)),
                ('burst_to', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=10)),
            ],
        ),
    ]
