# Generated by Django 5.1.3 on 2024-11-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genshincalc', '0014_charcalc'),
    ]

    operations = [
        migrations.AddField(
            model_name='charcalc',
            name='character_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='charcalc',
            name='level',
            field=models.IntegerField(choices=[(1, 1), (20, 20), (40, 40), (50, 50), (60, 60), (70, 70), (80, 80), (90, 90)], default=1),
        ),
    ]
