# Generated by Django 5.1.3 on 2024-11-27 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genshincalc', '0015_charcalc_character_id_alter_charcalc_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='charcalc',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='charcalc',
            name='character_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='genshincalc.character'),
        ),
    ]
