# Generated by Django 5.1.3 on 2024-11-27 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genshincalc', '0016_charcalc_id_alter_charcalc_character_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charcalc',
            name='id',
        ),
        migrations.AlterField(
            model_name='charcalc',
            name='character_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='genshincalc.character'),
        ),
    ]
