# Generated by Django 5.1.3 on 2024-11-27 02:04

import genshincalc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genshincalc', '0017_remove_charcalc_id_alter_charcalc_character_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='charcalc',
            name='level_from',
            field=models.IntegerField(choices=[(1, 1), (20, 20), (40, 40), (50, 50), (60, 60), (70, 70), (80, 80)], default=1),
        ),
        migrations.AddField(
            model_name='charcalc',
            name='level_to',
            field=models.IntegerField(choices=[(20, 20), (40, 40), (50, 50), (60, 60), (70, 70), (80, 80), (90, 90)], default=90),
        ),
        migrations.AlterField(
            model_name='charcalc',
            name='burst_from',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=1),
        ),
        migrations.AlterField(
            model_name='charcalc',
            name='burst_to',
            field=models.IntegerField(choices=[(2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=10),
        ),
        migrations.AlterField(
            model_name='charcalc',
            name='level',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='charcalc',
            name='na_from',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=1),
        ),
        migrations.AlterField(
            model_name='charcalc',
            name='na_to',
            field=models.IntegerField(choices=[(2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=10),
        ),
        migrations.AlterField(
            model_name='charcalc',
            name='skill_from',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=1),
        ),
        migrations.AlterField(
            model_name='charcalc',
            name='skill_to',
            field=models.IntegerField(choices=[(2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=10),
        ),
    ]
