# Generated by Django 5.1.3 on 2024-11-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genshincalc', '0018_charcalc_level_from_charcalc_level_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charcalc',
            name='na_to',
            field=models.IntegerField(choices=[(2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=10),
        ),
    ]
