# Generated by Django 5.1.3 on 2024-11-28 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genshincalc', '0019_alter_charcalc_na_to'),
    ]
