# Generated by Django 5.1.3 on 2024-11-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genshincalc', '0020_alter_charactermapping_boss_id_and_more'),
    ]

