# Generated by Django 5.1.3 on 2024-11-28 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genshincalc', '0021_alter_charactermapping_boss_id_and_more'),
    ]
'''
    operations = [
        migrations.RenameField(
            model_name='charactermapping',
            old_name='boss_id',
            new_name='boss_id_id',
        ),
        migrations.RenameField(
            model_name='charactermapping',
            old_name='character_id',
            new_name='character_id_id',
        ),
        migrations.RenameField(
            model_name='charactermapping',
            old_name='gem_2_id',
            new_name='gem_2_id_id',
        ),
        migrations.RenameField(
            model_name='charactermapping',
            old_name='regular_mob_1_id',
            new_name='regular_mob_1_id_id',
        ),
        migrations.RenameField(
            model_name='charactermapping',
            old_name='specialty_id',
            new_name='specialty_id_id',
        ),
        migrations.RenameField(
            model_name='charactermapping',
            old_name='talent_2_id',
            new_name='talent_2_id_id',
        ),
        migrations.RenameField(
            model_name='charactermapping',
            old_name='weekly_boss_id',
            new_name='weekly_boss_id_id',
        ),
    ]
'''