# Generated by Django 5.1.3 on 2024-11-28 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genshincalc', '0022_rename_boss_id_charactermapping_boss_id_id_and_more'),
    ]

