# Generated by Django 5.1.3 on 2024-11-28 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genshincalc', '0024_alter_weaponmapping_weapon_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weaponmapping',
            name='ascension_2_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genshincalc.weaponascension'),
        ),
        migrations.AlterField(
            model_name='weaponmapping',
            name='elite_mob_2_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genshincalc.elitemob'),
        ),
        migrations.AlterField(
            model_name='weaponmapping',
            name='regular_mob_1_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genshincalc.regularmob'),
        ),
    ]
