# Generated by Django 5.1.3 on 2024-11-28 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genshincalc', '0025_alter_weaponmapping_ascension_2_id_and_more'),
    ]
