# Generated by Django 5.1.3 on 2024-11-28 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genshincalc', '0028_alter_charactermapping_boss_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CharacterMapping',
        ),
    ]
