# Generated by Django 5.1.3 on 2024-11-28 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genshincalc', '0029_delete_charactermapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterMapping',
            fields=[
                ('character_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='genshincalc.character')),
                ('boss_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genshincalc.normalboss')),
                ('gem_2_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genshincalc.gem')),
                ('regular_mob_1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genshincalc.regularmob')),
                ('specialty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genshincalc.localspeciality')),
                ('talent_2_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genshincalc.talentbook')),
                ('weekly_boss_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genshincalc.weeklyboss')),
            ],
        ),
    ]
