# Generated by Django 5.1.3 on 2024-11-29 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genshincalc', '0031_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
