# Generated by Django 5.1.3 on 2024-11-29 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genshincalc', '0036_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charcalc',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='genshincalc.profile'),
        ),
    ]
