# Generated by Django 5.1.3 on 2024-11-29 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genshincalc', '0038_charcalc_id_alter_charcalc_character_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charcalc',
            name='character_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genshincalc.character'),
        ),
    ]
