# Generated by Django 5.1.3 on 2024-11-29 22:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genshincalc', '0039_alter_charcalc_character_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='charcalc',
            name='time_accessed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
