# Generated by Django 5.1.3 on 2024-11-30 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genshincalc', '0040_charcalc_time_accessed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weaponmapping',
            name='elite_mob_2_id',
        ),
        migrations.RemoveField(
            model_name='weaponmapping',
            name='weapon_id',
        ),
        migrations.RemoveField(
            model_name='weaponmapping',
            name='ascension_2_id',
        ),
        migrations.RemoveField(
            model_name='weaponmapping',
            name='regular_mob_1_id',
        ),
        migrations.DeleteModel(
            name='EliteMob',
        ),
        migrations.DeleteModel(
            name='Weapon',
        ),
        migrations.DeleteModel(
            name='WeaponAscension',
        ),
        migrations.DeleteModel(
            name='WeaponMapping',
        ),
    ]
