# Generated by Django 5.1.3 on 2024-11-30 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genshincalc', '0041_remove_weaponmapping_elite_mob_2_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exp',
            name='rarity',
        ),
        migrations.RemoveField(
            model_name='gem',
            name='rarity',
        ),
        migrations.RemoveField(
            model_name='regularmob',
            name='rarity',
        ),
        migrations.RemoveField(
            model_name='talentbook',
            name='rarity',
        ),
    ]
