# Generated by Django 5.1.3 on 2024-11-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genshincalc', '0045_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='element',
            field=models.CharField(choices=[('Anemo', 'Anemo'), ('Cryo', 'Cryo'), ('Dendro', 'Dendro'), ('Electro', 'Electro'), ('Geo', 'Geo'), ('Hydro', 'Hydro'), ('Pyro', 'Pyro')], max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='rarity',
            field=models.IntegerField(choices=[('★★★★', 4), ('★★★★★', 5)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='weapon_type',
            field=models.CharField(choices=[('Bow', 'Bow'), ('Catalyst', 'Catalyst'), ('Claymore', 'Claymore'), ('Polearm', 'Polearm'), ('Sword', 'Sword')], max_length=100),
        ),
    ]
