# Generated by Django 5.1.3 on 2024-11-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genshincalc', '0046_alter_character_element_alter_character_rarity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='rarity',
            field=models.IntegerField(choices=[(4, '★★★★'), (5, '★★★★★')]),
        ),
    ]
